modules:
  backbone.layer1.0: mb_k3e1
  backbone.layer2.0: mb_k5e3
  backbone.layer2.1: mb_k5e3
  backbone.layer2.2: identity
  backbone.layer2.3: mb_k3e3
  backbone.layer3.0: mb_k3e3
  backbone.layer3.1: identity
  backbone.layer3.2: identity
  backbone.layer3.3: mb_k3e3
  backbone.layer4.0: mb_k7e6
  backbone.layer4.1: identity
  backbone.layer4.2: mb_k7e3
  backbone.layer4.3: mb_k7e3
  backbone.layer5.0: mb_k3e3
  backbone.layer5.1: mb_k3e3
  backbone.layer5.2: mb_k7e3
  backbone.layer5.3: mb_k5e3
  backbone.layer6.0: mb_k5e6
  backbone.layer6.1: mb_k7e3
  backbone.layer6.2: mb_k7e3
  backbone.layer6.3: mb_k7e3
  backbone.layer7.0: mb_k5e6
channels:
